let packageDirString = ".packages"
let generatedDirString = ".generated"
let winRTProjectionsDirString = "WinRTProjections"
let swiftWinRTId = "TheBrowserCompany.SwiftWinRT"
let win2DId = "Microsoft.Graphics.Win2D"
let windowsAppSDKId = "Microsoft.WindowsAppSDK"
let canvasDllString = "Microsoft.Graphics.Canvas.dll"
let windowsAppRuntimeDllString = "Microsoft.WindowsAppRuntime.Bootstrap.dll"
